Reset state after identifier clash error
fixes a bug in the REPL:

    >>> fn f(h) = 1
    error: identifier clash in definition
        ┌─ Module 'units::si', File /usr/share/numbat/modules/units/si.nbt:126:6
        │
    126 │ unit hour: Time = 60 minutes
        │      ---- Previously defined here
        │
        ┌─ <input:1>:1:6
        │
      1 │ fn f(h) = 1
        │      ^ identifier is already in use

    >>> fn f(h_) = 1
    error: identifier clash in definition
      ┌─ <input:1>:1:4
      │
    1 │ fn f(h) = 1
      │    - Previously defined here
      │
      ┌─ <input:2>:1:4
      │
    1 │ fn f(h_) = 1
      │    ^ identifier is already in use

closes #143